title: Simanta Deb Turja # name of the site
author: Simanta Deb Turja # name of site's author
tag: 💻 Software Engineer
email: simantaturja@gmail.com # email of site's author
emailoffice: simanta.deb@cefalo.com
github: https://github.com/simantaturja
linkedin: https://linkedin.com/in/simantaturja
twitter: https://twitter.com/imturja
facebook: https://facebook.com/SD.Turja
url: 'https://simantaturja.github.io' # root address of the site
baseurl: '' # subpath of the site, e.g. "/blog"
description: > # description of the site (multiple lines allowed)
  A passionate Software Engineer

permalink: /:slug

favicon: 'turja.jpeg' # name+extension of favicon (which must be put on the root folder)
# goat_counter: "yoursitename" # put your GoatCounter name if you want to use GoatCounter analytics

#theme: no-style-please
remote_theme: no-style-please # if you are using GitHub Pages, change it to remote_theme: riggraz/no-style-please

theme_config:
  appearance: 'auto' # can be "light", "dark" or "auto"
  back_home_text: '<-back' # customize text for homepage link in post layout
  date_format: '%Y-%m-%d' # customize how date is formatted
  show_description: false # show blog description in home page

sass:
  style: :compressed
  
gems:
  - jekyll-font-awesome-sass
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-seo-tag

